import { Inter } from "next/font/google";
import "./globals.scss";
import MyContextProvider from "@/context/Context"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yemma Cooking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MyContextProvider>
    <html lang="fr">
      <body className={inter.className}>{children}</body>
    </html>
    </MyContextProvider>
  );
}
